In [2]:
import pandas as pd
import numpy as np
import pickle
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [3]:
df =pd.read_csv('IceCreamData.csv')

In [4]:
df.head()

Temperature     Revenue
0    24.566884  534.799028
1    26.005191  625.190122
2    27.790554  660.632289
3    20.595335  487.706960
4    11.503498  316.240194

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB


In [6]:
x=df['Temperature']
y=df['Revenue']

In [7]:
print(x)

0      24.566884
1      26.005191
2      27.790554
3      20.595335
4      11.503498
         ...    
495    22.274899
496    32.893092
497    12.588157
498    22.362402
499    28.957736
Name: Temperature, Length: 500, dtype: float64


In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [9]:
len(x_train)

400

In [10]:
len(x_test
    )

100

In [11]:
y_test.ndim

1

In [12]:
np.array([x_train]).ndim

2

In [13]:
model=LinearRegression()

In [14]:
model.fit((np.array([x_train]).reshape(-1,1)),y_train)

LinearRegression()

In [15]:
y_pred=model.predict(np.array(x_test).reshape(-1,1))

In [16]:
y_pred

array([416.7903487 , 510.41358792, 448.26684027, 570.38603528,
       404.0797524 , 400.96474649, 527.45861543, 577.33059668,
       253.51394549, 493.67859394, 627.86658482, 494.40518625,
       737.79622271, 458.81900551, 231.87773048, 531.63807482,
       495.18541545, 622.70662736, 606.15496659, 549.12289387,
       318.69937725, 572.35941788, 199.20017852, 638.95240158,
       621.20068973, 663.50739777, 872.17249289, 309.43891699,
       504.86548196, 316.21083754, 658.7793173 , 861.87062189,
       502.68427951, 456.77497435, 511.00240219, 582.40173591,
       526.71640623, 241.18113282, 642.8391521 , 797.26251079,
       607.9032252 , 873.01239176, 332.78155208, 600.95229411,
       723.59132822, 137.90458927, 414.43641275, 267.92274301,
       586.06306118, 591.86826235, 796.72117018, 662.11774543,
       368.32452846, 576.11628592, 235.2131335 , 212.81691932,
       891.05188347, 521.19712003, 629.90022038, 612.28642685,
        53.15823246, 524.88819721, 640.56303053, 740.57

In [17]:
y_test

421    405.915159
367    478.598509
69     430.343903
302    558.636932
488    379.318226
          ...    
152    319.402903
450    683.544781
359    384.699415
183    520.853456
357    498.252146
Name: Revenue, Length: 100, dtype: float64

In [18]:
r2_score(y_test,y_pred)

0.981445443316615

In [19]:
model.predict([[34]])

array([773.34759657])

In [21]:
model.predict([[1.69]])

array([83.53828638])

In [22]:
with open('model.pkl','wb') as files:
    pickle.dump(model,files)